# Generated by Django 5.1.4 on 2025-02-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectsphere', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
